DAB_PoseModification {
 m_sName "asdasd"
 m_aBoneModifications {
  DAB_BoneModification "{68FAEA79DBFB1AD0}" {
   m_sBoneName "RightForeArm"
   m_vRotationOffset 26.994 0 45.114
   m_vPositionOffset 0 0 0
   m_fScale 1
  }
  DAB_BoneModification "{68FAEA79DBFB1A32}" {
   m_sBoneName "Neck3"
   m_vRotationOffset 0 -21.931 0
   m_vPositionOffset 0 0 0
   m_fScale 1
  }
  DAB_BoneModification "{68FAEA79DBFB1A02}" {
   m_sBoneName "LeftArm"
   m_vRotationOffset 2.668 32.854 -60.246
   m_vPositionOffset 0 0 0
   m_fScale 1
  }
  DAB_BoneModification "{68FAEA79DBFB1A17}" {
   m_sBoneName "LeftForeArm"
   m_vRotationOffset -45.34 -6.988 7.481
   m_vPositionOffset 0 0 0
   m_fScale 1
  }
  DAB_BoneModification "{68FAEA79DBFB1A18}" {
   m_sBoneName "RightForeArmTwist"
   m_vRotationOffset 0 0 -68.552
   m_vPositionOffset 0 0 0
   m_fScale 1
  }
  DAB_BoneModification "{68FAEA79DBFB1A6A}" {
   m_sBoneName "RightLegTwist"
   m_vRotationOffset 0 148.892 0
   m_vPositionOffset 0 0 0
   m_fScale 1
  }
  DAB_BoneModification "{68FAEA79DBFB1A7D}" {
   m_sBoneName "LeftToe"
   m_vRotationOffset 0 -47.164 0
   m_vPositionOffset 0 0 0
   m_fScale 1
  }
  DAB_BoneModification "{68FAEA79DBFB1A4F}" {
   m_sBoneName "Spine4"
   m_vRotationOffset 0 -67.819 0
   m_vPositionOffset 0 0 0
   m_fScale 1
  }
  DAB_BoneModification "{68FAEA79DBFB1A50}" {
   m_sBoneName "RightArmTwist"
   m_vRotationOffset 2.233 0 0
   m_vPositionOffset 0 0 0
   m_fScale 1
  }
  DAB_BoneModification "{68FAEA79DBFB1BA5}" {
   m_sBoneName "Head"
   m_vRotationOffset -11.634 -22.14 0
   m_vPositionOffset 0 0 0
   m_fScale 1
  }
 }
}